  name: falixnodes
  version: '32.95.10'
  summary: A quick access to your servers
  description: |
    The FalixNodes application was built for users to have a quicker access to their FalixNodes client, panel, servers, and more all through one place. We also include our help center and uptime in there if needed.

  grade: stable
  confinement: strict
  
  parts:
    electron-quick-start:
      plugin: nil
      source: https://github.com/electron/electron-quick-start.git
      override-build: |
          sudo snap install node --classic
          npm install electron@9.4.4 electron-packager
          npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
          cp -rv ./electron-quick-start-linux-* $SNAPCRAFT_PART_INSTALL/electron-quick-start
      build-packages:
      - unzip
      stage-packages:
      - libnss3
      - libnspr4
