  name: falixnodes
  version: '32.95.10'
  summary: A quick access to your servers
  description: |
    The FalixNodes application was built for users to have a quicker access to their FalixNodes client, panel, servers, and more all through one place. We also include our help center and uptime in there if needed.

  grade: stable
  confinement: strict

parts:
  nodejs: 
    source: .
    plugin: nodejs
    nodejs-version: "12.13.1"
    nodejs-package-manager: "yarn"
    nodejs-yarn-version: "v1.21.1"
