name: Create Awesome Badge
on:
  workflow_dispatch:
jobs:
  generate-badge:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: schneegans/dynamic-badges-action@v1.1.0
    - with:
        label: Latest Version
        message: v3.1.0
        color: blue